name: Generate Sticker Manifest

on:
  push:
    paths:
      - stickers/**
  workflow_dispatch:

jobs:
  build-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Generate JSON manifest
        run: python scripts/gen-manifest.py

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet manifest.json; then
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes_detected == 'true'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: update `manifest.json`"
          file_pattern: manifest.json
